version: "3.8"
services:
  redis:
    container_name: "room-cache-redis"
    image: redis
    ports:
      - "6379:6379"
    restart: on-failure
    volumes:
      - ./redis-data:/data #change
    command: redis-server --requirepass admin
