server:
  port: 9990
  zoneId: "Europe/Moscow"

spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: true
        format_sql: true
        hbm2ddl:
          auto: none
        temp:
          use_jdbc_metadata_defaults: false
  flyway:
    baseline-on-migrate: true
    locations: db/migration
    enabled: false


socket:
  dest-prefixes: /topic, /queue
  user-prefix: /user
  app-prefix: /app
  endpoint: /api/room/chat
  chat-topic: /topic/messages
  youtube-topic: /topic/youtube
  private-message-topic: /queue/private
  header-room-id: roomId
  message-size-limit: 65536
  send-time-limit: 100000
  buffer-size-limit: 524288

chat-event:
  core-pool-size: 10
  max-pool-size: 10

jwt:
  header: Authorization
  prefix: "Bearer "
  role-claim: role

redis:
  master:
    port: 6379
    host: localhost
    password: admin

  replicas:
    - port: 6380
      host: localhost
    - port: 6381
      host: localhost

logging:
  level:
    ru.veselov: INFO
    org.testcontainers: INFO
    org.springframework.security: INFO
    org.springframework.web.socket: INFO
    org.springframework.messaging: INFO
    org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG

local:
  chatUserStub: disabled