server:
  port: 9990
  zoneId: "Europe/Moscow"

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5435/HarvexDB
    username: admin
    password: admin
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: true
        format_sql: true
        hbm2ddl:
          auto: none

  flyway:
    baseline-on-migrate: true
    locations: db/migration
    enabled: false


socket:
  dest-prefixes: /topic, /queue
  user-prefix: /user
  app-prefix: /app
  endpoint: /api/room/chat
  chat-topic: /topic/messages
  youtube-topic: /topic/youtube
  private-message-topic: /queue/private
  header-room-id: roomId
  message-size-limit: 65536
  send-time-limit: 100000
  buffer-size-limit: 524288

chat-event:
  core-pool-size: 10
  max-pool-size: 10

auth:
  header: Authorization
  prefix: "Bearer "
  role-claim: role
  chat-event-url: "/api/room/event"
  secret: "D9D323C5E55F45C206D7880329B1721A4334C00F336E5F2F1E9DAB745FF44837"

redis:
  master:
    port: 6379
    host: localhost
    password: admin

  replicas:
    - port: 6380
      host: localhost
    - port: 6381
      host: localhost

logging:
  level:
    ru.veselov: INFO
    org.testcontainers: INFO
    org.springframework.security: INFO
    org.springframework.web.socket: INFO
    org.springframework.messaging: INFO

local:
  chatUserStub: disabled