server:
  port: 9990
  zoneId: "Europe/Moscow"

socket:
  dest-prefixes: /topic, /queue
  user-prefix: /user
  app-prefix: /app
  endpoint: /api/room/chat
  chat-topic: /topic/messages
  youtube-topic: /topic/youtube
  private-message-topic: /queue/private
  header-room-id: roomId
  message-size-limit: 65536
  send-time-limit: 100000
  buffer-size-limit: 524288

chat-event:
  core-pool-size: 10
  max-pool-size: 10

spring:
  security:
    user:
      name: user1
      password: secret
      roles: USER

  profiles:
    active: local


redis:
  master:
    port: 6379
    host: localhost
    password: admin

  replicas:
    - port: 6380
      host: localhost
    - port: 6381
      host: localhost

  pool:
    max-total: 8
    max-idle: 8
    min-idle: 0

logging:
  level:
    ru.veselov: INFO
    org.springframework.web.socket: INFO