server:
  port: 9990

socket:
  dest-prefix: "/topic"
  app-prefix: "/app"
  endpoint: "/api/room/chat"
  users-topic: "/topic/users"

spring:
  security:
    user:
      name: user1
      password: secret
      roles: USER

logging:
  level:
    ru.veselov: INFO