server:
  port: 9990

socket:
  dest-prefixes: /topic, /queue
  user-prefix: /user
  app-prefix: /app
  endpoint: /api/room/chat
  chat-topic: /topic/messages
  private-message-topic: /queue/private
  header-room-id: roomId
  message-size-limit: 65536
  send-time-limit: 100000
  buffer-size-limit: 524288

chat-event:
  core-pool-size: 10
  max-pool-size: 10

spring:
  security:
    user:
      name: user1
      password: secret
      roles: USER
  data:
    redis:
      port: 6379
      host: localhost
      password: admin

logging:
  level:
    ru.veselov: INFO

local.stub: disabled