create table tag
(
    tag_id     int GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name       varchar(255) UNIQUE                  NOT NULL,
    primary key (tag_id),
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP
);

create table room_tag
(
    room_id UUID NOT NULL,
    tag_id  int  NOT NULL,
    primary key (room_id, tag_id),
    constraint room_tag_fk1
        foreign key (room_id) references public.room (id),
    constraint room_tag_fk2
        foreign key (tag_id) references public.tag (tag_id)
)